"""create models

Revision ID: 2263041e9466
Revises: 
Create Date: 2024-02-22 22:29:03.834255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2263041e9466"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("auther", sa.String(length=80), nullable=False),
        sa.Column("isbn", sa.String(length=13), nullable=True),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("publication_date", sa.DateTime(), nullable=False),
        sa.Column("publisher", sa.String(length=80), nullable=False),
        sa.Column("edition", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("cover_image_url", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_table(
        "book_by_attributes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("attribute", sa.String(length=20), nullable=False),
        sa.Column("value", sa.String(length=50), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("availibility", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory")
    op.drop_table("book_by_attributes")
    op.drop_table("book")
    # ### end Alembic commands ###
